### ISSUE TITLE
Create data schema

### ISSUE THREAD

**Issue by davidsharff** [davidsharff/gonfalon-sports-book#3]
#We need an idea of our basic data schema early on. These problems are likely in @MortalLimit 's wheelhouse -- at a minimum I'll run my ideas by him upfront.

GraphQL is intriguing for iterative design/development and can tie into our database of choice later on.

I could see us storing data in flat files to start. We can worry about true persistence later.

**Comment by davidsharff** [comment]
First pass at the schema below (expressed in YAML for readability). We'll start with only a redux server and write the resulting JSON to disk after each transaction.

@NateMeyvis let me know if you have any thoughts.
``` yaml

# app-state
  users:
    - id: key # can't key on username because they can be changed.
      email: string
    ...

  props:
    - id: key
      description: string
    ...

  propGroups: # TODO: is there a better noun for these?
    - id: key
      operator: string # Greater, Occurs First, etc.
      props:
        - propId: propForeignKey
          startingLine: number
        - propId: propForeignKey
          startingLine: number
    ...

  wagers: 
    - id: key
      playerId: userForeignKey
      propGroupId: propGroupForeignKey
    ...

# server-local-state (best guess, really depends on auth decisions)
  sessions:
    - authToken: string
      userId: userForeignKey
    ....

 # client-local-state
  # Note: may not be needed initially. Only reason I can think of is if we need to wait
  # for server confirmation before allowing subsequent actions.
```

**Comment by davidsharff** [comment]
I'm no longer convinced that `props` should exist apart from `propGroups`. I feel like it's normalizing the data for it's own sake. I can think of no time we'd want to list a prop independent of its group. Maybe we may want to reuse a prop in other groups one day, but I think it's preferable not to worry about it for now.

**Comment by davidsharff** [comment]
Update

Since lines will ultimately be dynamic, we need to store the "locked-in" line for each wager. This value can also be used to potentially calculate market value when buy-backs are supported.

```
wagers: 
    - id: key
      playerId: userForeignKey
      propGroupId: propGroupForeignKey
      line: number # as of time of the wager
```
